"""Secure AST-based interpreter for CaMeL execution plans."""

from __future__ import annotations

import ast
import operator
from typing import TYPE_CHECKING, Any, Callable, Awaitable

from loguru import logger

from nanobot.camel.capabilities import (
    CapabilityValue,
    TrustLevel,
    propagate_taint,
    wrap_literal,
    wrap_trusted,
    wrap_untrusted,
    unwrap,
)
from nanobot.camel.policies import PolicyEngine, PolicyViolation

if TYPE_CHECKING:
    from nanobot.agent.tools.registry import ToolRegistry
    from nanobot.camel.q_llm import QuarantinedLLM


class SecurityError(Exception):
    """Raised when a security violation is detected in the interpreter."""

    pass


class InterpreterError(Exception):
    """Raised when the interpreter encounters an error."""

    pass


# Q-LLM callback type
QLLMCallback = Callable[[str, CapabilityValue], Awaitable[CapabilityValue]]


class CamelInterpreter:
    """
    Secure AST-based interpreter for CaMeL execution plans.

    Executes P-LLM generated pseudo-Python while:
    - Tracking capabilities on all values
    - Enforcing security policies before tool execution
    - Mediating Q-LLM calls for data extraction
    """

    # Safe builtins that can be used in generated code
    ALLOWED_BUILTINS = {
        "len",
        "str",
        "int",
        "float",
        "bool",
        "list",
        "dict",
        "range",
        "enumerate",
        "zip",
        "min",
        "max",
        "sum",
        "sorted",
        "reversed",
        "abs",
        "round",
        "True",
        "False",
        "None",
        "print",  # For debugging, output goes to logs
    }

    # Binary operators
    BINARY_OPS = {
        ast.Add: operator.add,
        ast.Sub: operator.sub,
        ast.Mult: operator.mul,
        ast.Div: operator.truediv,
        ast.FloorDiv: operator.floordiv,
        ast.Mod: operator.mod,
        ast.Pow: operator.pow,
        ast.Eq: operator.eq,
        ast.NotEq: operator.ne,
        ast.Lt: operator.lt,
        ast.LtE: operator.le,
        ast.Gt: operator.gt,
        ast.GtE: operator.ge,
        ast.And: lambda a, b: a and b,
        ast.Or: lambda a, b: a or b,
        ast.In: lambda a, b: a in b,
        ast.NotIn: lambda a, b: a not in b,
    }

    # Unary operators
    UNARY_OPS = {
        ast.USub: operator.neg,
        ast.UAdd: operator.pos,
        ast.Not: operator.not_,
    }

    def __init__(
        self,
        tools: ToolRegistry,
        policy_engine: PolicyEngine,
        q_llm: QuarantinedLLM,
    ):
        self.tools = tools
        self.policy_engine = policy_engine
        self.q_llm = q_llm
        self._locals: dict[str, CapabilityValue] = {}
        self._last_result: CapabilityValue | None = None

    async def execute(
        self,
        code: str,
        user_context: dict[str, Any] | None = None,
    ) -> CapabilityValue | None:
        """
        Execute P-LLM generated code with security enforcement.

        Args:
            code: Python code generated by P-LLM
            user_context: Optional dict of user-provided values (trusted)

        Returns:
            The result of the last expression, or None
        """
        # Reset state
        self._locals = {}
        self._last_result = None

        # Initialize user-provided values as trusted
        if user_context:
            for name, value in user_context.items():
                self._locals[name] = wrap_trusted(value, origin="user")

        # Parse code
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            raise InterpreterError(f"Invalid code syntax: {e}")

        # Execute statements
        for node in tree.body:
            result = await self._visit(node)
            if result is not None:
                self._last_result = result

        return self._last_result

    async def _visit(self, node: ast.AST) -> CapabilityValue | None:
        """Visit an AST node and return a CapabilityValue."""
        method_name = f"_visit_{type(node).__name__}"
        method = getattr(self, method_name, None)

        if method is None:
            raise InterpreterError(
                f"Unsupported syntax: {type(node).__name__}. "
                "Only simple Python constructs are allowed."
            )

        return await method(node)

    # === Statement visitors ===

    async def _visit_Module(self, node: ast.Module) -> CapabilityValue | None:
        """Visit module (top-level)."""
        result = None
        for stmt in node.body:
            result = await self._visit(stmt)
        return result

    async def _visit_Expr(self, node: ast.Expr) -> CapabilityValue | None:
        """Visit expression statement."""
        return await self._visit(node.value)

    async def _visit_Assign(self, node: ast.Assign) -> None:
        """Handle variable assignment."""
        value = await self._visit(node.value)

        for target in node.targets:
            if isinstance(target, ast.Name):
                self._locals[target.id] = value
            elif isinstance(target, ast.Tuple):
                # Handle tuple unpacking
                if not isinstance(value.value, (list, tuple)):
                    raise InterpreterError("Cannot unpack non-sequence")
                for i, elt in enumerate(target.elts):
                    if isinstance(elt, ast.Name):
                        item_val = value.value[i]
                        self._locals[elt.id] = CapabilityValue(
                            value=item_val,
                            trust_level=value.trust_level,
                            origin=value.origin,
                            capabilities=value.capabilities.copy(),
                        )
            else:
                raise InterpreterError(f"Unsupported assignment target: {type(target)}")

    async def _visit_AugAssign(self, node: ast.AugAssign) -> None:
        """Handle augmented assignment (+=, -=, etc.)."""
        if not isinstance(node.target, ast.Name):
            raise InterpreterError("Augmented assignment only supported for simple names")

        current = self._locals.get(node.target.id)
        if current is None:
            raise InterpreterError(f"Name '{node.target.id}' is not defined")

        right = await self._visit(node.value)
        op_func = self.BINARY_OPS.get(type(node.op))

        if op_func is None:
            raise InterpreterError(f"Unsupported operator: {type(node.op)}")

        result_val = op_func(unwrap(current), unwrap(right))
        result_trust = propagate_taint([current, right])

        self._locals[node.target.id] = CapabilityValue(
            value=result_val,
            trust_level=result_trust,
            origin="derived",
            capabilities={},
        )

    async def _visit_For(self, node: ast.For) -> None:
        """Handle for loops."""
        iterable = await self._visit(node.iter)
        iter_val = unwrap(iterable)

        if not hasattr(iter_val, "__iter__"):
            raise InterpreterError("Cannot iterate over non-iterable")

        for item in iter_val:
            if isinstance(node.target, ast.Name):
                self._locals[node.target.id] = CapabilityValue(
                    value=item,
                    trust_level=iterable.trust_level,
                    origin=iterable.origin,
                    capabilities=iterable.capabilities.copy(),
                )
            elif isinstance(node.target, ast.Tuple):
                if not isinstance(item, (list, tuple)):
                    raise InterpreterError("Cannot unpack non-sequence in for loop")
                for i, elt in enumerate(node.target.elts):
                    if isinstance(elt, ast.Name):
                        self._locals[elt.id] = CapabilityValue(
                            value=item[i],
                            trust_level=iterable.trust_level,
                            origin=iterable.origin,
                            capabilities=iterable.capabilities.copy(),
                        )

            for stmt in node.body:
                await self._visit(stmt)

    async def _visit_If(self, node: ast.If) -> None:
        """Handle if statements."""
        test = await self._visit(node.test)

        if unwrap(test):
            for stmt in node.body:
                await self._visit(stmt)
        else:
            for stmt in node.orelse:
                await self._visit(stmt)

    async def _visit_Pass(self, node: ast.Pass) -> None:
        """Handle pass statement."""
        pass

    # === Expression visitors ===

    async def _visit_Call(self, node: ast.Call) -> CapabilityValue:
        """Handle function calls — the core security enforcement point."""
        func_name = self._get_func_name(node)

        # Evaluate arguments
        args = [await self._visit(arg) for arg in node.args]
        kwargs = {kw.arg: await self._visit(kw.value) for kw in node.keywords}

        # Special handling for Q-LLM calls
        if func_name == "query_quarantined_llm":
            return await self._handle_q_llm_call(args, kwargs)

        # Tool invocation
        if self.tools.has(func_name):
            return await self._execute_tool(func_name, args, kwargs)

        # Built-in functions
        if func_name in self.ALLOWED_BUILTINS:
            return await self._execute_builtin(func_name, args, kwargs)

        raise SecurityError(
            f"Function '{func_name}' is not allowed. "
            f"Available tools: {', '.join(self.tools.tool_names)}"
        )

    async def _execute_tool(
        self,
        tool_name: str,
        args: list[CapabilityValue],
        kwargs: dict[str, CapabilityValue],
    ) -> CapabilityValue:
        """Execute a tool with policy enforcement."""
        tool = self.tools.get(tool_name)
        if tool is None:
            raise InterpreterError(f"Tool '{tool_name}' not found")

        # Map positional args to parameter names
        param_schema = tool.parameters.get("properties", {})
        param_names = list(param_schema.keys())
        all_params: dict[str, CapabilityValue] = {}

        for i, arg in enumerate(args):
            if i < len(param_names):
                all_params[param_names[i]] = arg

        all_params.update(kwargs)

        # SECURITY: Validate against policies BEFORE execution
        logger.debug("Validating tool call: {}({})", tool_name, list(all_params.keys()))
        await self.policy_engine.validate(tool_name, all_params)

        # Execute with unwrapped values
        raw_params = {k: unwrap(v) for k, v in all_params.items()}

        try:
            result = await tool.execute(**raw_params)
        except Exception as e:
            logger.error("Tool {} failed: {}", tool_name, e)
            raise InterpreterError(f"Tool '{tool_name}' failed: {e}")

        # Wrap result with appropriate capabilities
        result_trust = self.policy_engine.get_result_trust(tool_name, all_params)
        result_caps = self.policy_engine.get_result_capabilities(tool_name)

        return CapabilityValue(
            value=result,
            trust_level=result_trust,
            origin=f"tool:{tool_name}",
            capabilities=result_caps,
        )

    async def _handle_q_llm_call(
        self,
        args: list[CapabilityValue],
        kwargs: dict[str, CapabilityValue],
    ) -> CapabilityValue:
        """Handle calls to the quarantined LLM for data extraction."""
        # Extract query and data arguments
        query = args[0] if args else kwargs.get("query")
        data = args[1] if len(args) > 1 else kwargs.get("data")

        if query is None:
            raise InterpreterError("query_quarantined_llm requires a query argument")
        if data is None:
            raise InterpreterError("query_quarantined_llm requires a data argument")

        query_str = unwrap(query)
        if not isinstance(query_str, str):
            query_str = str(query_str)

        # Q-LLM results are ALWAYS untrusted
        result = await self.q_llm.extract(query_str, data)

        logger.debug("Q-LLM extraction complete, result marked as UNTRUSTED")

        return result  # Already wrapped as untrusted by Q-LLM

    async def _execute_builtin(
        self,
        func_name: str,
        args: list[CapabilityValue],
        kwargs: dict[str, CapabilityValue],
    ) -> CapabilityValue:
        """Execute a built-in function."""
        raw_args = [unwrap(a) for a in args]
        raw_kwargs = {k: unwrap(v) for k, v in kwargs.items()}

        # Get the builtin
        if func_name == "True":
            return wrap_literal(True)
        if func_name == "False":
            return wrap_literal(False)
        if func_name == "None":
            return wrap_literal(None)
        if func_name == "print":
            # Log instead of print
            logger.info("print: {}", " ".join(str(a) for a in raw_args))
            return wrap_literal(None)

        builtin_func = __builtins__.get(func_name) if isinstance(__builtins__, dict) else getattr(__builtins__, func_name, None)

        if builtin_func is None:
            raise InterpreterError(f"Builtin '{func_name}' not found")

        result = builtin_func(*raw_args, **raw_kwargs)

        # Propagate taint from arguments
        result_trust = propagate_taint(args) if args else TrustLevel.TRUSTED

        return CapabilityValue(
            value=result,
            trust_level=result_trust,
            origin="builtin",
            capabilities={"can_display": True},
        )

    async def _visit_Name(self, node: ast.Name) -> CapabilityValue:
        """Visit a name (variable reference)."""
        if node.id in self._locals:
            return self._locals[node.id]

        # Check for builtin constants
        if node.id == "True":
            return wrap_literal(True)
        if node.id == "False":
            return wrap_literal(False)
        if node.id == "None":
            return wrap_literal(None)

        raise InterpreterError(f"Name '{node.id}' is not defined")

    async def _visit_Constant(self, node: ast.Constant) -> CapabilityValue:
        """Visit a constant (literal value)."""
        # Literals in P-LLM code are trusted (came from user query transformation)
        return wrap_literal(node.value)

    async def _visit_Str(self, node: ast.Str) -> CapabilityValue:
        """Visit string literal (Python 3.7 compat)."""
        return wrap_literal(node.s)

    async def _visit_Num(self, node: ast.Num) -> CapabilityValue:
        """Visit numeric literal (Python 3.7 compat)."""
        return wrap_literal(node.n)

    async def _visit_List(self, node: ast.List) -> CapabilityValue:
        """Visit list literal."""
        elements = [await self._visit(elt) for elt in node.elts]
        values = [unwrap(e) for e in elements]
        trust = propagate_taint(elements) if elements else TrustLevel.TRUSTED

        return CapabilityValue(
            value=values,
            trust_level=trust,
            origin="literal",
            capabilities={"can_display": True},
        )

    async def _visit_Dict(self, node: ast.Dict) -> CapabilityValue:
        """Visit dict literal."""
        keys = [await self._visit(k) if k else wrap_literal(None) for k in node.keys]
        values = [await self._visit(v) for v in node.values]

        result = {unwrap(k): unwrap(v) for k, v in zip(keys, values)}
        trust = propagate_taint(keys + values) if keys or values else TrustLevel.TRUSTED

        return CapabilityValue(
            value=result,
            trust_level=trust,
            origin="literal",
            capabilities={"can_display": True},
        )

    async def _visit_Tuple(self, node: ast.Tuple) -> CapabilityValue:
        """Visit tuple literal."""
        elements = [await self._visit(elt) for elt in node.elts]
        values = tuple(unwrap(e) for e in elements)
        trust = propagate_taint(elements) if elements else TrustLevel.TRUSTED

        return CapabilityValue(
            value=values,
            trust_level=trust,
            origin="literal",
            capabilities={"can_display": True},
        )

    async def _visit_BinOp(self, node: ast.BinOp) -> CapabilityValue:
        """Visit binary operation."""
        left = await self._visit(node.left)
        right = await self._visit(node.right)

        op_func = self.BINARY_OPS.get(type(node.op))
        if op_func is None:
            raise InterpreterError(f"Unsupported operator: {type(node.op)}")

        result = op_func(unwrap(left), unwrap(right))
        trust = propagate_taint([left, right])

        return CapabilityValue(
            value=result,
            trust_level=trust,
            origin="derived",
            capabilities={"can_display": True},
        )

    async def _visit_UnaryOp(self, node: ast.UnaryOp) -> CapabilityValue:
        """Visit unary operation."""
        operand = await self._visit(node.operand)

        op_func = self.UNARY_OPS.get(type(node.op))
        if op_func is None:
            raise InterpreterError(f"Unsupported unary operator: {type(node.op)}")

        result = op_func(unwrap(operand))

        return CapabilityValue(
            value=result,
            trust_level=operand.trust_level,
            origin=operand.origin,
            capabilities=operand.capabilities.copy(),
        )

    async def _visit_Compare(self, node: ast.Compare) -> CapabilityValue:
        """Visit comparison expression."""
        left = await self._visit(node.left)
        result = True
        all_operands = [left]

        current = left
        for op, comparator in zip(node.ops, node.comparators):
            right = await self._visit(comparator)
            all_operands.append(right)

            op_func = self.BINARY_OPS.get(type(op))
            if op_func is None:
                raise InterpreterError(f"Unsupported comparison: {type(op)}")

            if not op_func(unwrap(current), unwrap(right)):
                result = False
                break

            current = right

        trust = propagate_taint(all_operands)

        return CapabilityValue(
            value=result,
            trust_level=trust,
            origin="derived",
            capabilities={"can_display": True},
        )

    async def _visit_BoolOp(self, node: ast.BoolOp) -> CapabilityValue:
        """Visit boolean operation (and/or)."""
        values = [await self._visit(v) for v in node.values]

        if isinstance(node.op, ast.And):
            result = all(unwrap(v) for v in values)
        else:  # Or
            result = any(unwrap(v) for v in values)

        trust = propagate_taint(values)

        return CapabilityValue(
            value=result,
            trust_level=trust,
            origin="derived",
            capabilities={"can_display": True},
        )

    async def _visit_IfExp(self, node: ast.IfExp) -> CapabilityValue:
        """Visit ternary expression (x if cond else y)."""
        test = await self._visit(node.test)

        if unwrap(test):
            return await self._visit(node.body)
        else:
            return await self._visit(node.orelse)

    async def _visit_Subscript(self, node: ast.Subscript) -> CapabilityValue:
        """Visit subscript (indexing/slicing)."""
        value = await self._visit(node.value)
        slice_val = await self._visit(node.slice)

        result = unwrap(value)[unwrap(slice_val)]

        return CapabilityValue(
            value=result,
            trust_level=value.trust_level,
            origin=value.origin,
            capabilities=value.capabilities.copy(),
        )

    async def _visit_Index(self, node: ast.Index) -> CapabilityValue:
        """Visit index (Python 3.8 compat)."""
        return await self._visit(node.value)

    async def _visit_Slice(self, node: ast.Slice) -> CapabilityValue:
        """Visit slice."""
        lower = unwrap(await self._visit(node.lower)) if node.lower else None
        upper = unwrap(await self._visit(node.upper)) if node.upper else None
        step = unwrap(await self._visit(node.step)) if node.step else None

        return wrap_literal(slice(lower, upper, step))

    async def _visit_Attribute(self, node: ast.Attribute) -> CapabilityValue:
        """Visit attribute access."""
        value = await self._visit(node.value)

        # Only allow safe attribute access
        SAFE_ATTRS = {"strip", "lower", "upper", "split", "join", "replace", "startswith", "endswith", "format"}

        if node.attr not in SAFE_ATTRS:
            # Allow access but log warning
            logger.debug("Attribute access: {}.{}", type(unwrap(value)).__name__, node.attr)

        result = getattr(unwrap(value), node.attr)

        return CapabilityValue(
            value=result,
            trust_level=value.trust_level,
            origin=value.origin,
            capabilities=value.capabilities.copy(),
        )

    async def _visit_JoinedStr(self, node: ast.JoinedStr) -> CapabilityValue:
        """Visit f-string."""
        parts = []
        all_values = []

        for v in node.values:
            val = await self._visit(v)
            all_values.append(val)
            parts.append(str(unwrap(val)))

        result = "".join(parts)
        trust = propagate_taint(all_values) if all_values else TrustLevel.TRUSTED

        return CapabilityValue(
            value=result,
            trust_level=trust,
            origin="derived",
            capabilities={"can_display": True},
        )

    async def _visit_FormattedValue(self, node: ast.FormattedValue) -> CapabilityValue:
        """Visit formatted value in f-string."""
        return await self._visit(node.value)

    def _get_func_name(self, node: ast.Call) -> str:
        """Extract function name from Call node."""
        if isinstance(node.func, ast.Name):
            return node.func.id
        elif isinstance(node.func, ast.Attribute):
            # For method calls, we need special handling
            # For now, just return the method name
            return node.func.attr
        raise InterpreterError(f"Unsupported function call syntax: {ast.dump(node.func)}")
